@startuml
rectangle authzmanage {
  rectangle authz基础库 as authz
}

authzmanage -> authz:缓存
authz -> authzmanage:运算

database 数据库 as db
authzmanage -.> db:读/启动时加载数据
authzmanage -> db:写

rectangle 前端页面 as front
authzmanage -> front:接口交互(CRUD)

rectangle 其他服务 as othersvc1

othersvc1 .--> authzmanage:1询问
authzmanage --> othersvc1:2授权
@enduml